### ISSUE TITLE
hashmap_put()  

### ISSUE THREAD

**Issue by QingruiHuang** [sheredom/hashmap.h#10]
https://github.com/sheredom/hashmap.h/blob/1053f40495733cc01df412a3bb76be48f34f9686/hashmap.h#L236

if (0 == m->data[index].in_use)
{
   m->data[index].in_use = 1;
   m->size++;
}

**Comment by sheredom** [comment]
Not sure what you mean here? More context would help (or a PR!)

**Comment by QingruiHuang** [comment]
hashmap_put() in the same key multiple times, the hashmap_num_entries() should not be increased。

**Comment by sheredom** [comment]
Fixed in https://github.com/sheredom/hashmap.h/commit/cadde368f07514437406b7b3bc2878ea94c8f302
