### ISSUE TITLE
crash when hashmap_create

### ISSUE THREAD

**Issue by FashGek** [sheredom/hashmap.h#11]
env: vscode2019+luasrc
the hashmap_create modiy the pointer which point to a global gM，the fuction modify the pointer to point to a memory not init succ, the data point is broken.
![1458177768](https://user-images.githubusercontent.com/2861035/104152120-a8edbb80-5419-11eb-8faa-78d9c3b41bdb.jpg)

**Comment by sheredom** [comment]
What is the type of `gM` in your `initPS` call?

**Comment by sheredom** [comment]
Need more info to be able to help you here, please reopen if you can provide!
