### ISSUE TITLE
Inconvenient memory management

### ISSUE THREAD

**Issue by LianYangCn** [sheredom/hashmap.h#13]
Hi, 

Thanks firstly!

Here you store the pointer of `key`:
https://github.com/sheredom/hashmap.h/blob/a8b1cde2941236c8b131108a139777b4acd8f94c/hashmap.h#L233

And here to remove them:
https://github.com/sheredom/hashmap.h/blob/a8b1cde2941236c8b131108a139777b4acd8f94c/hashmap.h#L282

It's just set the element to zero. 

Test code:
```c
{
  char* key = strdup("test_key");
  void* data = malloc(8);

  hashmap_put(h,key,strlen(key), data);
}

/* huge code here*/

{
  hashmap_remove(h, "test_key", strlen("test_key")) // Memory LEAK?
  
  /* or */
  free(key);
  free(data);
}
```

How can I get the previous `key` pointer?

**Comment by sheredom** [comment]
Could you check out #14 for me? I hope it fixes your issue!

**Comment by LianYangCn** [comment]
Hi, @sheredom 
```
c

{
  char* key = strdup("test_key");
  void* data = malloc(8);

  hashmap_put(h,key,strlen(key), data);
}

/* huge code here*/

{
  hashmap_remove(h, "test_key", strlen("test_key")) // Memory LEAK?
  
  /* or */
  free(key);
  free(data);
}
'''
