### ISSUE TITLE
How to really release a hash node?

### ISSUE THREAD

**Issue by dafeilove** [sheredom/hashmap.h#34]
In most cases, memory needs to be allocated using malloc() for both key and value to be used properly, so when releasing a node, free() needs to be executed synchronously. How to delete a hash node for a specific key value? Using hashmap_remove can only delete but not actually release the memory that needs to be freed.

Is it only possible to match key values through hashmap_iterate_pairs() and then use free() to achieve actual release?
Best regards!

**Comment by sheredom** [comment]
Heh this is a fun one. Not sure what the fix would be to be honest. We'd need a `hashmap_remove_and_return_everything` or something that'd give you back the key and value.

**Comment by dafeilove** [comment]
Thanks for your reply.

Yes. I never thought about modifying and adding code myself before. I've added code like below to solve the problem.

struct hashmap_element_s *hashmap_remove_and_return_element(struct hashmap_s *const m,
                            const void *const key,
                            const hashmap_uint32_t len) {
  hashmap_uint32_t i, curr;
  struct hashmap_element_s *p;

  if ((HASHMAP_NULL == key) || (0 == len)) {
    return HASHMAP_NULL;
  }

  curr = hashmap_hash_helper_int_helper(m, key, len);

  /* Linear probing, if necessary */
  for (i = 0; i < HASHMAP_LINEAR_PROBE_LENGTH; i++) {
    const hashmap_uint32_t index = curr + i;

    if (m->data[index].in_use) {
      if (m->comparer(m->data[index].key, m->data[index].key_len, key, len)) {
        p = &m->data[index];
        /* Blank out the fields */
        memset(&m->data[index], 0, sizeof(struct hashmap_element_s));

        /* Reduce the size */
        m->size--;

        return p;
      }
    }
  }

  return HASHMAP_NULL;
}



***@***.***
 
From: Neil Henning
Date: 2023-11-22 17:00
To: sheredom/hashmap.h
CC: dafeilove; State change
Subject: Re: [sheredom/hashmap.h] How to really release a hash node? (Issue #34)
Heh this is a fun one. Not sure what the fix would be to be honest. We'd need a hashmap_remove_and_return_everything or something that'd give you back the key and value.

**Comment by sheredom** [comment]
Ah nice one! Glad you sorted it for yourself!
