### ISSUE TITLE
hashmap_create allows initial_size of 0

### ISSUE THREAD

**Issue by iamscottmoyers** [sheredom/hashmap.h#5]
The power of 2 check in `hashmap_create` allows an `initial_size` of 0, which causes a few problems, I think it should have been rejected.
https://github.com/sheredom/hashmap.h/blob/3636c6dc115daee91087beb097ce96f9366a7609/hashmap.h#L203

e.g. it's undefined whether the `calloc` later in the call will cause `hashmap_create` to return 0 or 1.

On macOS `hashmap_create(0, &hashmap)` succeeds, but if you then call `hashmap_get` you get a divide by zero exception.
https://github.com/sheredom/hashmap.h/blob/3636c6dc115daee91087beb097ce96f9366a7609/hashmap.h#L257

Not allowing zero sized hashmaps also covers the case in `hashmap_rehash_helper` where `2 * m->table_size` could overflow resulting in a `new_size` of 0, and removes the need for the `(0 == m->table_size)` check.
https://github.com/sheredom/hashmap.h/blob/3636c6dc115daee91087beb097ce96f9366a7609/hashmap.h#L490

**Comment by sheredom** [comment]
Good catch! Fancy doing a PR?

**Comment by iamscottmoyers** [comment]
Created #6 

...trying to figure out how to link issues and PRs correctly, I'm not sure I've succeeded :).
